name: "Kavita"
description: "Fast, feature-rich, cross-platform reading server for manga, comics, ebooks and more"
version: "0.9.0.2-ls120"
slug: "kavita"
url: "https://github.com/sjauijn/kavita-HAOS"
init: false
apparmor: true
startup: services
boot: auto
arch:
  - amd64
  - aarch64
map:
  - type: data
    read_only: false
  - type: share
    read_only: false
  - type: media
    read_only: false
  - type: ssl
    read_only: true
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "Kavita web interface"
webui: "[PROTO:ssl]://[HOST]:[PORT:5000]"
options:
  data_location: "/share/kavita"
  tz: "Europe/Paris"
  ssl: false
  certfile: "fullchain.pem"
  keyfile: "privkey.pem"
  log_level: "Information"
schema:
  data_location: "str"
  tz: "str"
  ssl: "bool"
  certfile: "str"
  keyfile: "str"
  log_level: "list(Fatal|Error|Warning|Information|Debug|Verbose)"
