name: "Kavita"
description: "Fast, feature-rich, cross-platform reading server for manga, comics, ebooks and more"
version: "1.0.0"
slug: "kavita"
url: "https://github.com/sjauijn/kavita-HAOS"
init: false
apparmor: false
startup: services
boot: auto
arch:
  - amd64
  - aarch64
map:
  - type: data
    read_only: false
  - type: share
    read_only: false
  - type: media
    read_only: false
  - type: ssl
    read_only: true
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: "Kavita web interface"
options:
  data_location: "/share/kavita"
  port: 5000
  tz: "Europe/Paris"
  ssl: false
  certfile: "fullchain.pem"
  keyfile: "privkey.pem"
schema:
  data_location: "str"
  port: "port"
  tz: "str"
  ssl: "bool"
  certfile: "str"
  keyfile: "str"
